import Footer from './components/Footer';
import Header from './components/Header'; // Ensure this path is correct
import { Metadata } from 'next'; // Or however you've defined your Metadata type
import { Inter } from 'next/font/google'; // If you're using the 'Inter' font from Google
import './globals.css';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });


import './globals.css';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="container">
          <Header></Header>
          <main>{children}</main>
          <Footer></Footer>
        </div>
      </body>
    </html>
  )
}


